export const adminFunctionalChecklist = [
  {
    page: "Applications",
    path: "/admin/applications",
    features: [
      "Search applications",
      "Filter by status",
      "Filter by AI flag",
      "Pagination",
      "Bulk status update",
      "Send notification",
      "SweetAlert confirmation",
    ],
    completed: true,
  },
  {
    page: "Programs",
    path: "/admin/programs",
    features: [
      "Create program",
      "Edit program",
      "Delete program",
      "Toggle program status",
      "Search programs",
      "Filter programs",
      "Dynamic stats",
      "SweetAlert confirmation",
    ],
    completed: true,
  },
  {
    page: "Users",
    path: "/admin/users",
    features: [
      "Create user",
      "Edit user",
      "Delete user",
      "Toggle user status",
      "Search users",
      "Filter users",
      "Dynamic stats",
      "SweetAlert confirmation",
    ],
    completed: true,
  },
  {
    page: "Legal Policies",
    path: "/admin/legal-policies",
    features: [
      "Create policy",
      "Edit policy",
      "Save draft",
      "Publish policy",
      "Archive policy",
      "Delete policy",
      "Search policies",
      "Dynamic stats",
    ],
    completed: true,
  },
  {
    page: "Admission Cycles",
    path: "/admin/admission-cycles",
    features: [
      "Create cycle",
      "Edit cycle",
      "Open cycle",
      "Close cycle",
      "Archive cycle",
      "Delete cycle",
      "Search cycles",
      "Dynamic stats",
    ],
    completed: true,
  },
  {
    page: "Notifications",
    path: "/admin/notifications",
    features: [
      "Create notification",
      "Send notification",
      "Schedule notification",
      "Save draft",
      "Delete notification",
      "Search notifications",
      "Dynamic stats",
    ],
    completed: true,
  },
  {
    page: "Document Verification",
    path: "/admin/document-verification",
    features: [
      "Select document",
      "Approve document",
      "Reject document",
      "Request re-upload",
      "Send note",
      "Search queue",
      "Update document status",
    ],
    completed: true,
  },
  {
    page: "Manual Review",
    path: "/admin/manual-review",
    features: [
      "Select review case",
      "View applicant details",
      "View AI summary",
      "Write reviewer notes",
      "Approve application",
      "Reject application",
      "Request fix",
      "Search queue",
      "Update application status",
    ],
    completed: true,
  },
] as const;